### ISSUE TITLE
getting system error while extracting wav file

### ISSUE THREAD

**Issue by amitesh-gaian** [v-iashin/video_features#1]
Error opening './tmp/v_ZNVhz7ctTq0.wav': System error.
Extraction failed at: ./sample/v_ZNVhz7ctTq0.mp4. Continuing extraction

**Comment by v-iashin** [comment]
Thanks for reporting.

Please uncomment
https://github.com/v-iashin/video_features/blob/da55152d9cb00fedab552e37ddc507defebbf220/models/vggish/extract_vggish.py#L7
and 
https://github.com/v-iashin/video_features/blob/da55152d9cb00fedab552e37ddc507defebbf220/models/vggish/extract_vggish.py#L66
to see the full trackback. Please share it here

**Comment by amitesh-gaian** [comment]
Enabling the traceback gave the issue. The issue was related to Cuda. Thanks for the reply
