### ISSUE TITLE
How to cite this project

### ISSUE THREAD

**Issue by CoderJackZhu** [v-iashin/video_features#122]
I use this project in a paper. I want to cite this this, could you please give me a cition like this:Citation
If you find this project useful in your research, please consider cite:

@misc{mmpose2020,
    title={OpenMMLab Pose Estimation Toolbox and Benchmark},
    author={MMPose Contributors},
    howpublished = {\url{https://github.com/open-mmlab/mmpose}},
    year={2020}
}

**Comment by v-iashin** [comment]
sure, use this one.

```bibtex
@misc{videofeatures2020,
  title = {Video Features},
  author = {Vladimir Iashin and other contributors},
  year = {2020},
  howpublished = {\url{https://github.com/v-iashin/video_features}},
}
```

good luck with your paper!
