### ISSUE TITLE
About i3d yml file

### ISSUE THREAD

**Issue by ajuhbw** [v-iashin/video_features#124]
Hi

When I executed conda env create -f conda_env_i3d.yml, the following error occurred.
`(base) D:\I3D_VGGish>conda env create -f conda_env_i3d.yml
Channels:
 - pytorch
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - zstd==1.3.7=h0b5b093_0
  - zlib==1.2.11=h7b6447c_3
  - xz==5.2.5=h7b6447c_0
  - x264==1!152.20180806=h7b6447c_0
  - tk==8.6.8=hbc83047_0
  - sqlite==3.31.1=h62c20be_1
  - readline==8.0=h7b6447c_0
  - pytorch==1.2.0=cuda100py37h938c94c_0
  - python==3.7.7=hcff3b4d_5
  - pillow==6.1.0=py37h34e0f95_0
  - openssl==1.1.1g=h7b6447c_0
  - openh264==1.8.0=hd408876_0
  - numpy-base==1.15.4=py37hde5b4d6_0
  - numpy==1.15.4=py37h7e9f1db_0
  - ninja==1.9.0=py37hfd86e86_0
  - nettle==3.4.1=hbb512f6_0
  - ncurses==6.2=he6710b0_1
  - nccl==1.3.5=cuda10.0_0
  - mkl_random==1.1.1=py37h0573a6f_0
  - mkl_fft==1.0.15=py37ha843d7b_0
  - mkl-service==2.3.0=py37he904b0f_0
  - mkl==2020.1=217
  - libtiff==4.1.0=h2733197_0
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - libpng==1.6.37=hbc83047_0
  - libiconv==1.15=h63c8f33_5
  - libgfortran-ng==7.3.0=hdf63c60_0
  - libgcc-ng==9.1.0=hdf63c60_0
  - libffi==3.3=he6710b0_1
  - libedit==3.1.20181209=hc058e9b_0
  - ld_impl_linux-64==2.33.1=h53a641e_7
  - lame==3.100=h7b6447c_0
  - jpeg==9b=h024ee3a_2
  - intel-openmp==2020.1=217
  - hdf5==1.10.2=hba1933b_1
  - h5py==2.8.0=py37h989c5e5_3
  - gnutls==3.6.5=h71b1129_1002
  - gmp==6.1.2=h6c8ec71_1
  - freetype==2.9.1=h8a8886c_1
  - ffmpeg==4.1.3=h167e202_0
  - fastrlock==0.4=py37he6710b0_0
  - cupy==5.1.0=py37hc0ce245_0
  - cffi==1.14.0=py37he30daa8_1
  - bzip2==1.0.8=h7b6447c_0

Current channels:

  - https://conda.anaconda.org/pytorch/win-64
  - https://conda.anaconda.org/conda-forge/win-64
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/msys2/win-64

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.`

How do I solve this problem?

**Comment by v-iashin** [comment]
Hey, sorry about that. You seem to be on windows.

try following this guide: https://v-iashin.github.io/video_features/meta/install_conda/

**Comment by ajuhbw** [comment]
> ねえ、ごめんなさい。あなたは窓にいるようです。
> 
> このガイドに従ってみてください: https://v-iashin.github.io/video_features/meta/install_conda/

I tried it, but I get the same error.

`(video_features) D:\I3D_VGGish>conda env create -f conda_env_i3d.yml
Channels:
 - pytorch
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - zstd==1.3.7=h0b5b093_0
  - zlib==1.2.11=h7b6447c_3
  - xz==5.2.5=h7b6447c_0
  - x264==1!152.20180806=h7b6447c_0
  - tk==8.6.8=hbc83047_0
  - sqlite==3.31.1=h62c20be_1
  - readline==8.0=h7b6447c_0
  - pytorch==1.2.0=cuda100py37h938c94c_0
  - python==3.7.7=hcff3b4d_5
  - pillow==6.1.0=py37h34e0f95_0
  - openssl==1.1.1g=h7b6447c_0
  - openh264==1.8.0=hd408876_0
  - numpy-base==1.15.4=py37hde5b4d6_0
  - numpy==1.15.4=py37h7e9f1db_0
  - ninja==1.9.0=py37hfd86e86_0
  - nettle==3.4.1=hbb512f6_0
  - ncurses==6.2=he6710b0_1
  - nccl==1.3.5=cuda10.0_0
  - mkl_random==1.1.1=py37h0573a6f_0
  - mkl_fft==1.0.15=py37ha843d7b_0
  - mkl-service==2.3.0=py37he904b0f_0
  - mkl==2020.1=217
  - libtiff==4.1.0=h2733197_0
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - libpng==1.6.37=hbc83047_0
  - libiconv==1.15=h63c8f33_5
  - libgfortran-ng==7.3.0=hdf63c60_0
  - libgcc-ng==9.1.0=hdf63c60_0
  - libffi==3.3=he6710b0_1
  - libedit==3.1.20181209=hc058e9b_0
  - ld_impl_linux-64==2.33.1=h53a641e_7
  - lame==3.100=h7b6447c_0
  - jpeg==9b=h024ee3a_2
  - intel-openmp==2020.1=217
  - hdf5==1.10.2=hba1933b_1
  - h5py==2.8.0=py37h989c5e5_3
  - gnutls==3.6.5=h71b1129_1002
  - gmp==6.1.2=h6c8ec71_1
  - freetype==2.9.1=h8a8886c_1
  - ffmpeg==4.1.3=h167e202_0
  - fastrlock==0.4=py37he6710b0_0
  - cupy==5.1.0=py37hc0ce245_0
  - cffi==1.14.0=py37he30daa8_1
  - bzip2==1.0.8=h7b6447c_0

Current channels:

  - https://conda.anaconda.org/pytorch/win-64
  - https://conda.anaconda.org/conda-forge/win-64
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/msys2/win-64

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.`

I ran this command in the video_features virtual environment. 
https://v-iashin.github.io/video_features/meta/install_conda/

**Comment by ajuhbw** [comment]
I'll try inserting it manually.
