### ISSUE TITLE
About the meaning of each number in the npy file

### ISSUE THREAD

**Issue by htowa** [v-iashin/video_features#127]
Hello

Your code worked fine!
When I applied the i3d model to the sample video and checked the shape of the npy file, I got (5, 1024).

Does 5 mean the number of frames?
Is it possible to apply i3d to all frames obtained from a video?
For example, if you have an 18 second video with fps of 30, the total number of frames is 240, will you get a result of (240, 1024)?

**Comment by v-iashin** [comment]
Hi. You have one feature per 64 frames by default. You can change it by modifying the stack size

**Comment by htowa** [comment]
> こんにちは。既定では、64 フレームごとに 1 つのフィーチャがあります。スタックサイズを変更することで変更できます

Oh, I mean. . .
For example, if the total number of frames is 240 and stack size is 64,

Total number of frames(240) / stack size(64) = about 3

is it right?

Also, please tell me the meaning and effect of step_size!

**Comment by v-iashin** [comment]
I see. Intuitively, step size is like a stride size and stack size is like a kernel size. So, if stack size is 64 and step size is 32 the features are extracted with half overlap.

**Comment by htowa** [comment]
> I see. Intuitively, step size is like a stride size and stack size is like a kernel size. So, if stack size is 64 and step size is 32 the features are extracted with half overlap.

I see, I understand!

Thx!
