### ISSUE TITLE
About saving npy files

### ISSUE THREAD

**Issue by htowa** [v-iashin/video_features#129]
sorry

When extracting features from a video and saving it as an npy file, it seems that "video_name_timestamps_ms and video_name_fps" are also saved together.

How can I avoid saving these files and only save "video_name_rgb"?

**Comment by v-iashin** [comment]
sorry about the super late reply.

it is easy to fix by commenting the keys you don't wanna save:

https://github.com/v-iashin/video_features/blob/1b67c9f8cfb44b61f6fae5fa1a89d34b7fe7a579/models/_base/base_framewise_extractor.py#L75-L79

and 

https://github.com/v-iashin/video_features/blob/1b67c9f8cfb44b61f6fae5fa1a89d34b7fe7a579/models/_base/base_flow_extractor.py#L96-L99

depending on the feature extractor you are using.

also, I'd love to merge a pull request that implements it.

**Comment by htowa** [comment]
> 返信が激遅くなってすみません。すっかり見落としてしまいました。
> 
> 保存したくないキーをコメントすることで簡単に修正できます。
> 
> https://github.com/v-iashin/video_features/blob/1b67c9f8cfb44b61f6fae5fa1a89d34b7fe7a579/models/_base/base_framewise_extractor.py#L75-L79
> 
> そして
> 
> https://github.com/v-iashin/video_features/blob/1b67c9f8cfb44b61f6fae5fa1a89d34b7fe7a579/models/_base/base_flow_extractor.py#L96-L99
> 
> 使用している特徴抽出器によって異なります。
> 
> また、それを実装するプルリクエストをマージしたいと思います。

I see, TXH!

**Comment by WuZhuoran** [comment]
Hi Author @v-iashin 

You defined this attribute:

https://github.com/v-iashin/video_features/blob/master/models/_base/base_framewise_extractor.py#L44

as `output_feat_key`, If we pass the value as `self.output_feat_keys = [self.feature_type]`, will it only save `feature_type` npy files?

**Comment by htowa** [comment]
Thx.
