### ISSUE TITLE
How to apply `transform` function for every frames in `VideoLoader`?

### ISSUE THREAD

**Issue by WuZhuoran** [v-iashin/video_features#130]
Hi Author,

I found that in this line:
https://github.com/v-iashin/video_features/blob/master/models/_base/base_framewise_extractor.py#L65

You defined the `transform` and it will use `self.transform` functions.

Also, you defined many transform functions here: https://github.com/v-iashin/video_features/blob/master/models/transforms.py

I want to know how to apply those transform function for videos?

In specific, I have a video with `(1080, 1080)` height, width size. And I only want the left half features, So I want to apply a transform function to crop and get the left `(540, 1080)`. How to do that?

Thank you

**Comment by v-iashin** [comment]
i am not sure if any of the supported video feature extractors were designed to process this kind of videos and, therefore, doesn't seem to be the problem of `video_features`.

suppose you have a video `video = torch.random(B, T, 3, H, W)` why can't you do `video[:, :, :, :, :540` will give you the left half. alternatively, you can use `crop(vid, 0, 0, 1080, 540)` to get what you want in terms of those transforms.

**Comment by WuZhuoran** [comment]
> i am not sure if any of the supported video feature extractors were designed to process this kind of videos and, therefore, doesn't seem to be the problem of `video_features`.
> 
> suppose you have a video `video = torch.random(B, T, 3, H, W)` why can't you do `video[:, :, :, :, :540` will give you the left half. alternatively, you can use `crop(vid, 0, 0, 1080, 540)` to get what you want in terms of those transforms.

Thanks for quick reply.

Yeah, This is not a problemk of `video_features`, I just want to know how to apply `crop(vid, 0 ,0, 1080, 540)` this functions to `VideoLoader`, it seems no config for that. If not implemented yet, I will modify the code directly.

Thank you
