### ISSUE TITLE
About centor ctop

### ISSUE THREAD

**Issue by htowa** [v-iashin/video_features#136]
Hi.

When extracting frame images from a video, are you applying the center frame image to I3D?
How can I apply the entire frame image to I3D?

**Comment by v-iashin** [comment]
hi,

it should be fine. try making sure you are getting the same output with your inputs as with the center crop in here: https://github.com/v-iashin/video_features/blob/1b67c9f8cfb44b61f6fae5fa1a89d34b7fe7a579/models/i3d/i3d_src/i3d_net.py#L257

you can tweak pre-processing (crop etc) here: 
- https://github.com/v-iashin/video_features/blob/1b67c9f8cfb44b61f6fae5fa1a89d34b7fe7a579/models/i3d/extract_i3d.py#L51
- https://github.com/v-iashin/video_features/blob/1b67c9f8cfb44b61f6fae5fa1a89d34b7fe7a579/models/i3d/extract_i3d.py#L56

**Comment by htowa** [comment]
If the input video size is H=240, W=320, is it possible to resize it to 224, 224 and input it into I3D?

**Comment by v-iashin** [comment]
I think it is. Change the min side size to 224. 

https://github.com/v-iashin/video_features/blob/1b67c9f8cfb44b61f6fae5fa1a89d34b7fe7a579/models/i3d/extract_i3d.py#L45

**Comment by htowa** [comment]
THX.
