### ISSUE TITLE
How to get each frame feature of I3D(rgb+flow)

### ISSUE THREAD

**Issue by Mythili-kannan** [v-iashin/video_features#141]
Lets say there are 400 frames in a video clip , how can i get rgb and flow features of shape(400,1024) and (400,1024) respectively.

can you please help me on this

**Comment by v-iashin** [comment]
go to google colab for i3d, and specify `stack_size=1`, `step_size=1`

**Comment by Mythili-kannan** [comment]
I tried it , its throwing error
RuntimeError: Calculated padded input size per channel: (6 x 229 x 229). Kernel size: (7 x 7 x 7). Kernel size can't be greater than actual input size

**Comment by v-iashin** [comment]
true, it is not possible with i3d then. it has 3d conv blocks which need at least 7 frames. you could get `400-stack_size+1` output frames. try finding the minimal that works.

**Comment by Mythili-kannan** [comment]
Thanks for the reply, will frame-based extractors help to get better feature to train action segmentation networks where the actions involves have temporal activity too
