### ISSUE TITLE
Warnings: NumPy and OMP: Warning #190

### ISSUE THREAD

**Issue by leftthomas** [v-iashin/video_features#15]
<img width="852" alt="image" src="https://user-images.githubusercontent.com/9991443/147149006-baa35b79-5cdb-4702-8b7f-0e496fd9ef1f.png">

**Comment by v-iashin** [comment]
Does it work?

**Comment by leftthomas** [comment]
It can work, and there are another warning, just too annoying
<img width="845" alt="image" src="https://user-images.githubusercontent.com/9991443/147176446-c272d2f3-3ac4-4fff-9e9a-1c0b166a7633.png">

**Comment by v-iashin** [comment]
Ok, #57 should fix the one the issue starter mentioned in the original post.

The latter one will be fixed when #42 is done as the extraction will no longer be multi-GPU

**Comment by v-iashin** [comment]
It should not complain with `OMP: Warning 190` anymore
