### ISSUE TITLE
Problem of processing short video

### ISSUE THREAD

**Issue by HaoShawnZheng** [v-iashin/video_features#17]
Thank you for providing such a good repo. It really helps me a lot.
However, my videos are very short with less than 100 frames. When I tried my videos on your Colab to extract I3D feautures. I got nothing. I guess it's the problem of the setting of step_size, stack_size, extraction_fps. But when I tried to set them all at 1, I still got nothinng. 
So, sorry for bothering you with this little problem. I am a fresh guy in coding. So, can you help out? 
Many thanks.

**Comment by v-iashin** [comment]
Hi there! I am glad you liked it. 

Don’t worry, we’ve all been there. Could you please share a video here so we could inspect it?

**Comment by HaoShawnZheng** [comment]
C0001P0001A0101T0001.avi
<https://drive.google.com/file/d/1XLsthcuZgPW2qPn1c2axLGe9oOaDEhdJ/view?usp=drive_web>
Thank you so much. Here is a video example. It's very large but very short.
I am considering reducing the size of the video.
I was taking this video into your colab, trying to extract i3d features. I
failed. The feature is null.
I am so grateful that you are willing to help me analyze the problem,
Many thanks.

Best regards,
Hao

**Comment by v-iashin** [comment]
Ok, as I anticipated, the issue was with the video uploading procedure which you have to solve yourself.

Here are the notebooks showing that the default parameters yield non-null feature stacks:
[i3d_and_r21d_notebooks.zip](https://github.com/v-iashin/video_features/files/7820062/i3d_and_r21d_notebooks.zip)
