### ISSUE TITLE
Add supports on Windows and CPU-only system

### ISSUE THREAD

**Issue by Kamino666** [v-iashin/video_features#26]
Hi, I'm very interested in this repo and I have a project based on it, and I've made some changes to a previous version of this repo(including adding new models, etc.)[Kamino666/video_features](https://github.com/Kamino666/video_features). Seeing that you have updated this repo, I would like to gradually add my previous changes to it. First I want to support Windows and CPU-only systems.

I understand that currently linux and GPU are generally used for deep learning, but adding support for windows and cpu can help people debug. And I don't think it will cause very big changes.

1. Windows
Basically, the incompatibility comes from this function, bacause Windows doesn't have `which` command, which can be replaced with `where` command.
```python
def which_ffmpeg() -> str:
    '''Determines the path to ffmpeg library

    Returns:
        str -- path to the library
    '''
    result = subprocess.run(['which', 'ffmpeg'], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    ffmpeg_path = result.stdout.decode('utf-8').replace('\n', '')
    return ffmpeg_path
```

2. cpu-only
A new item needs to be added to the configuration to specify whether or not to use the GPU, and some minor changes need to be made in main.py. However, in my tests, the PWC model does not work with the CPU, and I am not very clear about this model.

Can I submit a PR to address the above issue?

——
@v-iashin : added backlog:
- [x] windows
- [ ] Cpu

**Comment by v-iashin** [comment]
Hi, @Kamino666 thanks for letting me know that you like the project.

Thanks for creating the issue. These two features I would love to have.

Let's go one by one, starting with Windows support. Could you form a PR changing just that? 

I don't have a Windows machine at my disposal, so it might be difficult for me to help you. However, it seems like you know what to do, please go ahead!

I may be slow to respond these weeks, sorry.

**Comment by Kamino666** [comment]
ok, I will update recently!

**Comment by Kamino666** [comment]
[PR #27](https://github.com/v-iashin/video_features/pull/27)

**Comment by v-iashin** [comment]
Thanks! Very nice!

Go ahead with the cpu. 

I think for pwc we can leave an assertion that the device should be gpu and fail otherwise. Could you also make a note in the pwc/i3d doc sections mentioning that only gpu is supported in pwc and advice to switch to raft or other vid features. 

Added a backlog to your comment.

**Comment by Kamino666** [comment]
No problem, I'll get started on these.

**Comment by Kamino666** [comment]
PR #28
