### ISSUE TITLE
CLIP reference and change log is missing

### ISSUE THREAD

**Issue by v-iashin** [v-iashin/video_features#34]
Hey @Kamino666

May I ask you to make a PR adding a header comment to the CLIP files? 

e.g.
```
'''
    Reference: https://github.com/openai/CLIP/tree/<hash-of-the-state-you-used>
    Modified by Kamino (@Kamino666):
      - change
'''
<content starts>
```

You don't have to add a very elaborate change log, just a sentence describing what has changed compared to the originals.

**Comment by Kamino666** [comment]
Sure, I'd like to do this.

**Comment by Kamino666** [comment]
#46
