### ISSUE TITLE
The output of `show_pred` may be confusing

### ISSUE THREAD

**Issue by Kamino666** [v-iashin/video_features#36]
Neither the documentation nor the program output mentions the meaning of each column, and now we have two outputs with the same format but different meanings.

examples:

Similarity | Probability | Sentences provided
```
23.061 0.962 a dog smiles
19.824 0.038 a woman is lifting

22.770 0.963 a dog smiles
19.520 0.037 a woman is lifting

24.619 0.929 a dog smiles
22.048 0.071 a woman is lifting
```

Logit | Probability | Label
```
33.584 0.594 a photo of snatch weight lifting
33.027 0.340 a photo of deadlifting
31.080 0.049 a photo of clean and jerk
28.425 0.003 a photo of situp
27.873 0.002 a photo of bench pressing
```

Do you think we should add some output to the code or explain it in the documentation?

**Comment by v-iashin** [comment]
Yees, thanks. I will fix it
