### ISSUE TITLE
typeerror

### ISSUE THREAD

**Issue by taruntiwarihp** [v-iashin/video_features#5]
(i3d) root@ever:~/video_features# python main.py --feature_type i3d --device_ids 0 2 --video_paths ./sample/v_ZNVhz7ctTq0.mp4 ./sample/v_GGSY1Qvo990.mp4
Traceback (most recent call last):
  File "main.py", line 94, in <module>
    sanity_check(args)
  File "/root/video_features/utils/utils.py", line 105, in sanity_check
    assert args.stack_size >= 10, message
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

**Comment by v-iashin** [comment]
Thanks for the catch. I introduced this bug in the previous commit.
