### ISSUE TITLE
The timestamps of some ending frames are 0

### ISSUE THREAD

**Issue by Kamino666** [v-iashin/video_features#68]
There are always a few frames at the end of the output feature with a timestamp of 0.

For example, when using `resnet-50` to extract the feature of `v_GGSY1Qvo990.mp4` at 2 fps, I got:
```
array([    0.,   500.,  1000.,  1500.,  2000.,  2500.,  3000.,  3500.,
        4000.,  4500.,  5000.,  5500.,  6000.,  6500.,  7000.,  7500.,
        8000.,  8500.,  9000.,  9500., 10000., 10500., 11000., 11500.,
       12000., 12500., 13000., 13500., 14000., 14500.,     0.,     0.,
           0.,     0.,     0.,     0.])
```

For another example, if I set `args.extraction_fps = 2` in [resnet colab example](https://colab.research.google.com/drive/17VLdf4abQT2eoMjc6ziJ9UaRaOklTlP0?usp=sharing), I got :
```
[    0.   500.  1000.  1500.  2000.  2500.  3000.  3500.  4000.  4500.
  5000.  5500.  6000.  6500.  7000.  7500.  8000.  8500.  9000.  9500.
 10000. 10500. 11000. 11500. 12000. 12500. 13000. 13500. 14000. 14500.
 15000. 15500. 16000. 16500.     0.     0.]
```

I think we could calculate the timestamp of the i-th frame by `i * (1 / fps)`, instead of `cap.get(cv2.CAP_PROP_POS_MSEC)`.

**Comment by v-iashin** [comment]
Yep, I saw. However, I could not reproduce it locally and I thought it is colab-related (the ffmpeg version). 

Have you tried to do it locally?

**Comment by Kamino666** [comment]
Yes, I have. The first example is the one that appears when running it locally.

Here is my running command:
`python main.py feature_type=resnet model_name=resnet50 extraction_fps=2 on_extraction=save_numpy batch_size=16 cpu=true video_paths="[./sample/v_ZNVhz7ctTq0.mp4, ./sample/v_GGSY1Qvo990.mp4]"`

Here is the version info of my `ffmpeg`:
```
ffmpeg version N-103022-gf614390ecc-20210721 Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10-win32 (GCC) 20210408
```

**Comment by v-iashin** [comment]
Seems like the change is harmless. Please form a PR.

Do you have any idea why it fails, by the way?

**Comment by Kamino666** [comment]
I don't know the exact reason, but all the similar fails I found online suggest using fps to calculate time (I forgot to save the link).

**Comment by v-iashin** [comment]
No problem

**Comment by v-iashin** [comment]
I think #70 fixes this
