### ISSUE TITLE
How to extract from whole dataset 

### ISSUE THREAD

**Issue by Dev-ori** [v-iashin/video_features#84]
Hi, thank you for your work.

Now I'm trying to extract Flow feature, from 'dataset' or 'directory' not the exact one 'file' 

As I can see through the **main.py** there is no argument for that. 

Would you give me a tip for modify it?

**Comment by v-iashin** [comment]
Hi. Thanks for letting me know.

Did you try something like this:
```bash
find ./dataset -name "*mp4" > ./video_paths.txt
```
and then use `./video_paths.txt` as an input to `main.py`?

Note, that it will not work if there are subfolders with files that have the same names. See #54.

**Comment by Dev-ori** [comment]
> Hi. Thanks for letting me know.
> 
> Did you try something like this:
> 
> ```shell
> find ./dataset -name "*mp4" > ./video_paths.txt
> ```
> 
> and then use `./video_paths.txt` as an input to `main.py`?
> 
> Note, that it will not work if there are subfolders with files that have the same names. See #54.

this works!! thank you very much.  +1:  your work really made my day. 

If this doesn't bother you, I want to ask you one more thing about Visualization. 

Is there a way to convert 000.npy(flow file from raft) to mp4 video? 

I've already check your flow_viz.py but it seems works Flow to Image. not the Video file. 

thx.

**Comment by v-iashin** [comment]
> Is there a way to convert 000.npy(flow file from raft) to mp4 video?

Yeees, it is on my TODO list (see #81).

By the way, if you would like to contribute it, I would be happy to merge it. No pressure, please do only if you think it would be fun. 

It should be also very easy to implement.

---
I am closing this as it is a documented feature.

**Comment by Dev-ori** [comment]
> > Is there a way to convert 000.npy(flow file from raft) to mp4 video?
> 
> Yeees, it is on my TODO list (see #81).
> 
> By the way, if you would like to contribute it, I would be happy to merge it. No pressure, please do only if you think it would be fun.
> 
> It should be also very easy to implement.
> 
> I am closing this as the original issue could be solved with a workaround.

Oh, maybe we are in the same page I guess. :smile: 

As far I searched, I've only could find the way that convert it through manually 
(file by file, not looping the whole dataset(npy,flow) to dataset(mp4)) 

If i could get the way, I'll love to share it on your TODO list (#81).  

Good day.
