### ISSUE TITLE
When the extraction_total parameter is set to 1, the problem of missing frames is encountered

### ISSUE THREAD

**Issue by ChenyuLy** [v-iashin/video_features#86]
Hi,I encountered a problem when I tried to extract a global feature for whole video.  I set extraction_total parameter  to 1.  But there is a problem When executing the ffmpeg instruction.  Is there a way to extract a global feature without video slice?
![image](https://user-images.githubusercontent.com/40486256/194745547-4f07460f-8659-4109-8305-9ea62d4a97da.png)

**Comment by v-iashin** [comment]
Hi, thanks a lot for making an issue. 

While I am trying to figure out why it is happening, try to use a higher value of extract total (eg 5) and then pick the middle item from the saved list

**Comment by v-iashin** [comment]
@Kamino666 what do you think? Should we warn users about using a single frame (assert). 

this is of course an option but it seems like a nice feature to have. The problem again with that the cv2. 

I will take a closer look later

**Comment by v-iashin** [comment]
@ChenyuLy By the way, you could try to average a few extracted features. I am not sure if it will work for your application but you run an experiment comparing averaging of 5 features vs 1 middle feature.

**Comment by v-iashin** [comment]
Hm, @ChenyuLy, do you still get some features on those failed examples?

**Comment by ChenyuLy** [comment]
I do get some features,because  not all videos will encounter this problem.  And  ,by the way, It seems that this result is not caused by the extraction_total  parameter being 1.


![image](https://user-images.githubusercontent.com/40486256/194750092-57f7fd79-7846-4b39-ae78-b34bdaab004c.png)

**Comment by ChenyuLy** [comment]
do you still get some features on those failed examples?

> Hm, @ChenyuLy, do you still get some features on those failed examples?

I do you get some features on those failed examples.

**Comment by ChenyuLy** [comment]
To be more specific, when I set the parameter to 1, I cannot get the failed examples feature. When I set the parameter to other values, I can get the failed examples feature.

**Comment by v-iashin** [comment]
Could you make a minimal (not) working example to reproduce the issue?

From what I understood, you get features on the failed examples and I think it is some sort of a middle frame. So, there is nothing to fix, is it?

Actually, this is not an error but a warning. Since the code does not fail with any error, I would just ignore it.

**Comment by ChenyuLy** [comment]
> 

Yes, it is just a warning.  I'm just a little worried about the effect of the feature .😂 Thanks for the reply and This is really a great repository

**Comment by v-iashin** [comment]
>  I'm just a little worried about the effect of the feature

As I see it: if a video has 250 frames and the first one is skipped that middle frame will be at around the same position anyway.
