### ISSUE TITLE
ResolvePackageNotFound for conda_env_pwc.yml

### ISSUE THREAD

**Issue by rabeya-akter** [v-iashin/video_features#97]
GIves this error while trying to do this:

conda env create -f conda_env_pwc.yml

Error:
Retrieving notices: ...working... done
Collecting package metadata (repodata.json): -done
Solving environment: failed

ResolvePackageNotFound: 
  - torchvision==0.4.0=py37_cu100
  - pytorch==1.2.0=py3.7_cuda10.0.130_cudnn7.6.2_0

**Comment by v-iashin** [comment]
Yeah, i think there is a problem with installing old packages with `conda` or something. I have got an issue with the same error message. https://github.com/v-iashin/BMT/issues/49

If you will be able to fix it, let me know by replying to this issue.

I think only the docker approach works now: https://iashin.ai/video_features/meta/docker/

**Comment by v-iashin** [comment]
Ok, I briefly looked into this and found out that build specification might have caused it.

People suggest using `conda env export --no-builds > env.yml` when exporting the environments as I mentioned in that issue.

Try replacing the corresponding lines in the .yaml file with:
```
  - torchvision=0.4.0
  - pytorch=1.2.0
```

**Comment by v-iashin** [comment]
Solved by replacing the build version everywhere
